#requires -Version 7.0
<#
.SYNOPSIS
    Deploy the Ask Fabric Mastery Azure OpenAI infrastructure and update the local .env file.

.DESCRIPTION
    Runs a subscription-scope Bicep deployment (resource group + Azure OpenAI account
    with chat & embedding deployments), then reads the outputs back to populate or
    update the local .env file consumed by the Streamlit app.

.PARAMETER SubscriptionId
    The Azure subscription id to deploy into. Defaults to the current `az account show` id.

.PARAMETER ResourceGroupName
    Name of the resource group to create. Default: rg-ask-fabric-mastery.

.PARAMETER Location
    Azure region. Default: eastus2.

.PARAMETER WhatIf
    Run `az deployment sub what-if` instead of `create`.

.PARAMETER SkipEnv
    Skip writing the .env file after deployment.

.EXAMPLE
    pwsh ./scripts/deploy_azure.ps1 -Location swedencentral

.EXAMPLE
    pwsh ./scripts/deploy_azure.ps1 -WhatIf
#>
[CmdletBinding()]
param(
    [string]$SubscriptionId,
    [string]$ResourceGroupName = 'rg-ask-fabric-mastery',
    [string]$Location = 'eastus2',
    [switch]$WhatIf,
    [switch]$SkipEnv
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true

$repoRoot = Split-Path -Parent $PSScriptRoot
$bicepFile = Join-Path $repoRoot 'infra' 'main.bicep'
$envFile = Join-Path $repoRoot '.env'

# Cognitive Services OpenAI User: read access for chat + embedding APIs
$OpenAiUserRoleId = '5e0bd9bd-7b93-4f28-af87-19fc36ad61bd'

function Assert-AzCli {
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        throw 'Azure CLI not found. Install it from https://aka.ms/azcli.'
    }
}

function Assert-AzLogin {
    $account = az account show 2>$null | ConvertFrom-Json
    if (-not $account) {
        Write-Host 'Not logged in. Launching az login...' -ForegroundColor Yellow
        az login --only-show-errors | Out-Null
        $account = az account show | ConvertFrom-Json
    }
    return $account
}

function Set-Subscription {
    param([string]$Id)
    if ($Id) {
        Write-Host "Switching to subscription $Id" -ForegroundColor Cyan
        az account set --subscription $Id | Out-Null
    }
}

function Invoke-Deployment {
    param([string]$DeploymentName)
    $deploymentArgs = @(
        'deployment', 'sub',
        ($WhatIf ? 'what-if' : 'create'),
        '--name', $DeploymentName,
        '--location', $Location,
        '--template-file', $bicepFile,
        '--parameters', "resourceGroupName=$ResourceGroupName", "location=$Location",
        '--only-show-errors'
    )
    Write-Host "Running: az $($deploymentArgs -join ' ')" -ForegroundColor Cyan
    if ($WhatIf) {
        az @deploymentArgs
        return $null
    }
    $deployment = az @deploymentArgs --output json | ConvertFrom-Json
    if (-not $deployment) { throw 'Deployment returned no output.' }
    return $deployment
}

function Get-AccountKey {
    param([string]$AccountName, [string]$Rg)
    try {
        $keys = az cognitiveservices account keys list `
            --name $AccountName --resource-group $Rg --only-show-errors 2>$null | ConvertFrom-Json
        if ($keys.key1) { return $keys.key1 }
    } catch {
        Write-Host "  Local key auth disabled on $AccountName (Entra ID required)." -ForegroundColor Yellow
    }
    return $null
}

function Get-AccountResourceId {
    param([string]$AccountName, [string]$Rg)
    return (az cognitiveservices account show --name $AccountName --resource-group $Rg `
        --query id --output tsv --only-show-errors)
}

function Get-SignedInPrincipalId {
    return (az ad signed-in-user show --query id --output tsv --only-show-errors)
}

function Grant-OpenAiUserRole {
    param([string]$Scope, [string]$PrincipalId)
    Write-Host "  Assigning 'Cognitive Services OpenAI User' on $Scope" -ForegroundColor Cyan
    az role assignment create `
        --assignee-object-id $PrincipalId `
        --assignee-principal-type User `
        --role $OpenAiUserRoleId `
        --scope $Scope `
        --only-show-errors 2>$null 1>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Role may already be assigned (idempotent skip)." -ForegroundColor DarkYellow
    }
}

function Write-EnvFile {
    param(
        [string]$Endpoint,
        [string]$Key,
        [string]$ChatDeployment,
        [string]$ChatModel,
        [string]$EmbeddingDeployment,
        [string]$EmbeddingModel
    )
    $keyLine = if ($Key) {
        "AZURE_OPENAI_API_KEY=$Key"
    } else {
        "# AZURE_OPENAI_API_KEY is intentionally empty: tenant requires Entra ID auth.`n# Run ``az login`` (or use a managed identity) before starting the app."
    }
    $content = @"
# Auto-generated by scripts/deploy_azure.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')

AZURE_OPENAI_ENDPOINT=$Endpoint
$keyLine
AZURE_OPENAI_API_VERSION=2024-10-21

AZURE_OPENAI_CHAT_DEPLOYMENT=$ChatDeployment
AZURE_OPENAI_CHAT_MODEL=$ChatModel

AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$EmbeddingDeployment
AZURE_OPENAI_EMBEDDING_MODEL=$EmbeddingModel

DATA_DIR=./data/newsletters
STORAGE_DIR=./storage/chroma
COLLECTION_NAME=fabric_mastery

CHUNK_SIZE=1024
CHUNK_OVERLAP=128

TOP_K=6
SIMILARITY_CUTOFF=0.35
TEMPERATURE=0.1
MAX_TOKENS=1024

DEFAULT_LANGUAGE=fr
"@
    Set-Content -Path $envFile -Value $content -Encoding utf8
    Write-Host "Wrote $envFile" -ForegroundColor Green
}

# ---------------------------------------------------------------------------
Assert-AzCli
$account = Assert-AzLogin
if (-not $SubscriptionId) { $SubscriptionId = $account.id }
Set-Subscription -Id $SubscriptionId

Write-Host "Subscription: $($account.name) [$SubscriptionId]" -ForegroundColor Green
Write-Host "Tenant:       $($account.tenantId)" -ForegroundColor Green
Write-Host "Location:     $Location" -ForegroundColor Green
Write-Host "RG:           $ResourceGroupName" -ForegroundColor Green

az provider register --namespace Microsoft.CognitiveServices --wait --only-show-errors | Out-Null

$deploymentName = "askfabric-$(Get-Date -Format 'yyyyMMddHHmmss')"
$deployment = Invoke-Deployment -DeploymentName $deploymentName
if ($WhatIf) { return }

$outputs = $deployment.properties.outputs
$endpoint = $outputs.openAiEndpoint.value
$accountName = $outputs.openAiName.value
$chatDeployment = $outputs.chatDeployment.value
$chatModel = $outputs.chatModel.value
$embeddingDeployment = $outputs.embeddingDeployment.value
$embeddingModel = $outputs.embeddingModel.value

Write-Host ''
Write-Host '=== Deployment outputs ===' -ForegroundColor Cyan
Write-Host "OpenAI endpoint:        $endpoint"
Write-Host "OpenAI account name:    $accountName"
Write-Host "Chat deployment:        $chatDeployment ($chatModel)"
Write-Host "Embedding deployment:   $embeddingDeployment ($embeddingModel)"
Write-Host ''

if ($SkipEnv) {
    Write-Host 'SkipEnv set — not updating .env.' -ForegroundColor Yellow
    return
}

$key = Get-AccountKey -AccountName $accountName -Rg $ResourceGroupName

if (-not $key) {
    Write-Host 'Configuring Entra ID auth (no API key available)...' -ForegroundColor Yellow
    $scope = Get-AccountResourceId -AccountName $accountName -Rg $ResourceGroupName
    $principalId = Get-SignedInPrincipalId
    if (-not $principalId) { throw 'Could not resolve signed-in user principal id.' }
    Grant-OpenAiUserRole -Scope $scope -PrincipalId $principalId
    Write-Host '  Entra ID role assignment requested. Token-based auth may take ~60s to propagate.' -ForegroundColor DarkYellow
}

Write-EnvFile `
    -Endpoint $endpoint `
    -Key $key `
    -ChatDeployment $chatDeployment `
    -ChatModel $chatModel `
    -EmbeddingDeployment $embeddingDeployment `
    -EmbeddingModel $embeddingModel

Write-Host 'Done. Next steps:' -ForegroundColor Green
Write-Host '  1. python -m scripts.ingest_substack'
Write-Host '  2. python -m scripts.build_index'
Write-Host '  3. streamlit run app.py'
